---
- name: ansible adminstration
  hosts: all
  tasks:
  - name: create a group
    group: 
     name: manage
     state: present
  - name: create another group
    group:
     name: security
     state: present
  - name: create a user
    user: 
     name: ruth
     uid: 51003
     shell: /bin/bash
     groups: manage, security
     append: true
  - name: Give privilege to the group 
    copy:
     content: '%manage ALL=(ALL) NOPASSWD: ALL'
     dest: /etc/sudoers.d/manage
  - name: Creating a ssh-key for user ruth
    user:
     name: ruth
     generate_ssh_key: true
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_my_rsa_ruth
