---
- name: demonstrate package management
  hosts: windows
  tasks:
    - name: Downloads files from HTTP, HTTPS, or FTP to the remote server
      win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\users\admin\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi

    - name: Installs or uninstalls a package in either an MSI
      win_package:
        path: C:\users\admin\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present

    - name: Manage packages using Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install git using Chocolatey
      win_chocolatey:
        name: git
        state: present
